name: Publish to NPM
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 26.1
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - run: yarn install --immutable
      - run: npm publish --provenance --access public
