name: test.yml
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 26.1
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - run: yarn install --immutable

      - run: yarn test --project unit
